package bucketfill

import (
	"bufio"
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path"
	"path/filepath"
	"strings"
	"text/template"
)

// EntryBinaryPath is the path (relative to the user's project root) of the
// scaffolded migrator main package.
const EntryBinaryPath = "cmd/migrate"

// ReadModulePath parses go.mod at the given path and returns the module path.
func ReadModulePath(goModPath string) (string, error) {
	f, err := os.Open(goModPath)
	if err != nil {
		return "", fmt.Errorf("bucketfill: open %s: %w", goModPath, err)
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if rest, ok := strings.CutPrefix(line, "module "); ok {
			return strings.TrimSpace(rest), nil
		}
	}
	if err := scanner.Err(); err != nil {
		return "", fmt.Errorf("bucketfill: read %s: %w", goModPath, err)
	}
	return "", fmt.Errorf("bucketfill: no module directive in %s", goModPath)
}

// migrationsPackageName returns the Go-package-style name for the basename of
// the configured migrations directory (e.g. "db/seeds" -> "seeds"). Falls back
// to "migrations" if the basename isn't a valid identifier-ish name.
func migrationsPackageName(migrationDir string) string {
	base := path.Base(filepath.ToSlash(migrationDir))
	// Replace non-alphanumeric chars with underscores; ensure it doesn't start with a digit.
	if base == "" || base == "." || base == "/" {
		return "migrations"
	}
	var b strings.Builder
	for i, r := range base {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r == '_':
			b.WriteRune(r)
		case r >= '0' && r <= '9':
			if i == 0 {
				b.WriteRune('_')
			}
			b.WriteRune(r)
		default:
			b.WriteRune('_')
		}
	}
	return b.String()
}

const entryBinaryTemplate = `// Code generated by bucketfill. Edit if you need custom registration logic;
// otherwise this file is safe to leave alone — adding new versions does not
// require regenerating it.
package main

import (
	"context"
	"log"
	"os"

	"github.com/n1kola-petrovic/bucketfill"
	_ "github.com/n1kola-petrovic/bucketfill/provider/gcs"
	_ "github.com/n1kola-petrovic/bucketfill/provider/s3"

	{{.PkgName}} "{{.ModulePath}}/{{.MigrationDir}}"
)

func main() {
	if err := bucketfill.RegisterFS({{.PkgName}}.FS); err != nil {
		log.Fatal(err)
	}
	if err := bucketfill.RunCLI(context.Background(), os.Args[1:]); err != nil {
		log.Fatal(err)
	}
}
`

type entryBinaryData struct {
	ModulePath   string
	MigrationDir string
	PkgName      string
}

// GenerateEntryBinary writes cmd/migrate/main.go in projectRoot if it doesn't
// already exist. Returns true when a file was written.
//
// Unlike previous bucketfill versions, this entry binary is static — adding
// new versions does not require regenerating it. Once written, treat it like
// any other source file: commit it, edit it if you need custom registration.
func GenerateEntryBinary(projectRoot, modulePath, migrationDir string) (bool, error) {
	tmpl, err := template.New("entry").Parse(entryBinaryTemplate)
	if err != nil {
		return false, fmt.Errorf("bucketfill: parse entry template: %w", err)
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, entryBinaryData{
		ModulePath:   modulePath,
		MigrationDir: migrationDir,
		PkgName:      migrationsPackageName(migrationDir),
	}); err != nil {
		return false, fmt.Errorf("bucketfill: render entry template: %w", err)
	}
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return false, fmt.Errorf("bucketfill: gofmt entry binary: %w\n--- source ---\n%s", err, buf.String())
	}

	dir := filepath.Join(projectRoot, EntryBinaryPath)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return false, fmt.Errorf("bucketfill: mkdir %s: %w", dir, err)
	}
	target := filepath.Join(dir, "main.go")
	if _, err := os.Stat(target); err == nil {
		return false, nil // already exists, leave alone
	}
	if err := os.WriteFile(target, formatted, 0o644); err != nil {
		return false, fmt.Errorf("bucketfill: write %s: %w", target, err)
	}
	return true, nil
}

const topEmbedTemplate = `// Code generated by bucketfill. The %[1]s glob auto-picks up new v<N>/
// directories — you do not need to regenerate this file when adding versions.
package %[2]s

import "embed"

//go:embed all:v*
var FS embed.FS
`

// EnsureMigrationsEmbed writes <migrationDir>/embed.go if missing. This is the
// single top-level embed file that exposes every v<N>/ subtree as one fs.FS.
func EnsureMigrationsEmbed(projectRoot, migrationDir string) (bool, error) {
	pkg := migrationsPackageName(migrationDir)
	target := filepath.Join(projectRoot, migrationDir, "embed.go")
	if _, err := os.Stat(target); err == nil {
		return false, nil
	}
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return false, fmt.Errorf("bucketfill: mkdir %s: %w", filepath.Dir(target), err)
	}
	content := fmt.Sprintf(topEmbedTemplate, "all:v*", pkg)
	formatted, err := format.Source([]byte(content))
	if err != nil {
		return false, fmt.Errorf("bucketfill: gofmt embed.go: %w", err)
	}
	if err := os.WriteFile(target, formatted, 0o644); err != nil {
		return false, fmt.Errorf("bucketfill: write %s: %w", target, err)
	}
	return true, nil
}

// ScaffoldVersion creates <migrationDir>/v<N>/data/.keep. The .keep file lets
// //go:embed succeed when the version's data folder is otherwise empty; PutAll
// skips it on upload.
//
// Custom Up/Down logic is opt-in: hand-write a v<N>/migration.go that defines
// Up/Down functions and explicitly Register() them in cmd/migrate/main.go
// before the call to RegisterFS — RegisterFS will skip versions already in
// the registry.
func ScaffoldVersion(projectRoot, migrationDir string, version int) (string, error) {
	pkg := fmt.Sprintf("v%d", version)
	versionDir := filepath.Join(projectRoot, migrationDir, pkg)
	dataDir := filepath.Join(versionDir, "data")
	if err := os.MkdirAll(dataDir, 0o755); err != nil {
		return "", fmt.Errorf("bucketfill: mkdir %s: %w", dataDir, err)
	}
	keep := filepath.Join(dataDir, ".keep")
	if _, err := os.Stat(keep); os.IsNotExist(err) {
		if err := os.WriteFile(keep, nil, 0o644); err != nil {
			return "", fmt.Errorf("bucketfill: write %s: %w", keep, err)
		}
	}
	return versionDir, nil
}
