package bucketfill

import (
	"bufio"
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// EntryBinaryPath is the path (relative to the user's project root) of the
// scaffolded main package that imports every version and dispatches the runner.
const EntryBinaryPath = "cmd/migrate"

// ReadModulePath parses go.mod at the given path and returns the module path.
func ReadModulePath(goModPath string) (string, error) {
	f, err := os.Open(goModPath)
	if err != nil {
		return "", fmt.Errorf("bucketfill: open %s: %w", goModPath, err)
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if rest, ok := strings.CutPrefix(line, "module "); ok {
			return strings.TrimSpace(rest), nil
		}
	}
	if err := scanner.Err(); err != nil {
		return "", fmt.Errorf("bucketfill: read %s: %w", goModPath, err)
	}
	return "", fmt.Errorf("bucketfill: no module directive in %s", goModPath)
}

const entryBinaryTemplate = `// Code generated by bucketfill. DO NOT EDIT.
package main

import (
	"context"
	"io/fs"
	"log"
	"os"

	"github.com/n1kola-petrovic/bucketfill"
	_ "github.com/n1kola-petrovic/bucketfill/provider/gcs"
	_ "github.com/n1kola-petrovic/bucketfill/provider/s3"
{{range .Versions}}
	{{.PkgName}} "{{$.ModulePath}}/{{$.MigrationDir}}/{{.PkgName}}"
{{- end}}
)

func main() {
{{range .Versions}}	bucketfill.Register(&bucketfill.Migration{
		Version: {{.Version}},
		Up:      {{.PkgName}}.Up,
		Down:    {{.PkgName}}.Down,
		Data:    sub({{.PkgName}}.Data),
	})
{{end}}
	if err := bucketfill.RunCLI(context.Background(), os.Args[1:]); err != nil {
		log.Fatal(err)
	}
}

func sub(efs fs.FS) fs.FS {
	if efs == nil {
		return nil
	}
	s, err := fs.Sub(efs, "data")
	if err != nil {
		return nil
	}
	return s
}
`

type entryBinaryData struct {
	ModulePath   string
	MigrationDir string
	Versions     []VersionDir
}

// GenerateEntryBinary writes (or rewrites) cmd/migrate/main.go in projectRoot.
// It returns true when the file changed on disk.
func GenerateEntryBinary(projectRoot, modulePath, migrationDir string, versions []VersionDir) (bool, error) {
	tmpl, err := template.New("entry").Parse(entryBinaryTemplate)
	if err != nil {
		return false, fmt.Errorf("bucketfill: parse entry template: %w", err)
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, entryBinaryData{
		ModulePath:   modulePath,
		MigrationDir: migrationDir,
		Versions:     versions,
	}); err != nil {
		return false, fmt.Errorf("bucketfill: render entry template: %w", err)
	}
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return false, fmt.Errorf("bucketfill: gofmt entry binary: %w\n--- source ---\n%s", err, buf.String())
	}

	dir := filepath.Join(projectRoot, EntryBinaryPath)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return false, fmt.Errorf("bucketfill: mkdir %s: %w", dir, err)
	}
	target := filepath.Join(dir, "main.go")
	return writeIfChanged(target, formatted)
}

const versionUpTemplate = `package %s

import (
	"context"

	"github.com/n1kola-petrovic/bucketfill"
)

// Up applies migration v%d. Use the client to upload from the data/ folder
// (c.Put / c.PutAll) or perform other bucket operations (c.Rename / c.Delete).
func Up(ctx context.Context, c *bucketfill.Client) error {
	// TODO: implement v%d up
	return nil
}
`

const versionDownTemplate = `package %s

import (
	"context"

	"github.com/n1kola-petrovic/bucketfill"
)

// Down reverses migration v%d. The same data/ folder is available to read from
// or to enumerate keys to delete from the bucket.
func Down(ctx context.Context, c *bucketfill.Client) error {
	// TODO: implement v%d down
	return nil
}
`

const versionEmbedTemplate = `// Code generated by bucketfill. Edit data/ to change uploaded assets.
package %s

import "embed"

//go:embed all:data
var Data embed.FS
`

// ScaffoldVersion creates migrations/v<N>/{up,down,embed}.go and data/.keep.
// It does NOT overwrite existing files (so re-running bucketfill new on the
// same version is a no-op for already-customized files).
func ScaffoldVersion(projectRoot, migrationDir string, version int) (string, error) {
	pkg := fmt.Sprintf("v%d", version)
	versionDir := filepath.Join(projectRoot, migrationDir, pkg)
	dataDir := filepath.Join(versionDir, "data")
	if err := os.MkdirAll(dataDir, 0o755); err != nil {
		return "", fmt.Errorf("bucketfill: mkdir %s: %w", dataDir, err)
	}

	files := map[string]string{
		"up.go":    fmt.Sprintf(versionUpTemplate, pkg, version, version),
		"down.go":  fmt.Sprintf(versionDownTemplate, pkg, version, version),
		"embed.go": fmt.Sprintf(versionEmbedTemplate, pkg),
	}
	for name, content := range files {
		p := filepath.Join(versionDir, name)
		if _, err := os.Stat(p); err == nil {
			continue // don't clobber user changes
		}
		formatted, err := format.Source([]byte(content))
		if err != nil {
			return "", fmt.Errorf("bucketfill: gofmt %s: %w", name, err)
		}
		if err := os.WriteFile(p, formatted, 0o644); err != nil {
			return "", fmt.Errorf("bucketfill: write %s: %w", p, err)
		}
	}

	keep := filepath.Join(dataDir, ".keep")
	if _, err := os.Stat(keep); os.IsNotExist(err) {
		if err := os.WriteFile(keep, nil, 0o644); err != nil {
			return "", fmt.Errorf("bucketfill: write %s: %w", keep, err)
		}
	}

	return versionDir, nil
}

// writeIfChanged writes content to path only when the file is missing or
// differs. Returns true if a write occurred.
func writeIfChanged(path string, content []byte) (bool, error) {
	existing, err := os.ReadFile(path)
	if err == nil && bytes.Equal(existing, content) {
		return false, nil
	}
	if err := os.WriteFile(path, content, 0o644); err != nil {
		return false, fmt.Errorf("bucketfill: write %s: %w", path, err)
	}
	return true, nil
}
